version: 2

jobs:
  build:
    working_directory: ~/blog
    docker:
      - image: circleci/python:3.5-browsers

    steps:
      - checkout
      - restore_cache:
          key: blog-v1-{{ .Branch }}-{{ checksum "dev-requirements.txt" }}

      - run:
          name: install python deps
          command: |
            python3 -m venv env
            . env/bin/activate
            pip install -r dev-requirements.txt

      - save_cache:
          key: blog-v1-{{ .Branch }}
          paths:
            - env

      - run:
          name: run tests
          command: |
            . env/bin/activate
            cp blog/settings.example.cfg blog/settings.cfg
            export BLOG_PATH=$(pwd) && coverage run --source blog -m unittest tests/**.py
            # flake8 --output-file=flake8.txt -j 4 blog
            coverage html

      - run:
          name: start app in background
          command: |
            . env/bin/activate
            script/run-dev.sh
          background: true

      - run:
          name: run functional tests
          command: |
            . env/bin/activate
            python -m unittest tests/functional/functional_tests.py

      - store_artifacts:
          path: htmlcov
