version: 2

jobs:
  build:
    working_directory: ~/blog
    docker:
      - image: circleci/python:3.5-browsers

    steps:
      - checkout
      - run: sudo pip install -r dev-requirements.txt
      - run: cp blog/settings.example.cfg blog/settings.cfg
      - run: export BLOG_PATH=$(pwd) && coverage run --source blog -m unittest tests/**.py
      - run: export BLOG_PATH=$(pwd) && flask run &
      - run: export BLOG_PATH=$(pwd) && python -m unittest tests/functional/**.py
      - run: flake8 --output-file=flake8.txt -j 4 blog
      - run: coverage html 
